### ISSUE TITLE
Some

### ISSUE THREAD

**Issue by Ashot94** [JohnRoyale/BachelorProject#1]
Hi JohnRoyale and voldelord. I am trying to do something like this and would like to ask you some questions.

**Comment by Ashot94** [comment]
please, answer me

**Comment by Remi-Niel** [comment]
Hi, sorry for the lack of response but we just had exam weeks, what kind of questions do you have?

**Comment by Ashot94** [comment]
Asa maybe we can talk via mail or some other way

**Comment by Ashot94** [comment]
maybe we can talk via mail or some other way?

**Comment by Remi-Niel** [comment]
I have sent a mail to the e-mail account you use for GitHub
